services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ../servicedesk-frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: "no"

volumes:
  mysql_data: